### ISSUE TITLE
alt_alleles_at_site_mod

### ISSUE THREAD

**Issue by antoine4ucsd** [liampshaw/CoV-homoplasy-filtering#1]
Hello
I am trying to apply your nice workflow to another set of COVID and eventually non COVID data.
I can't find the alt_alleles_at_site_mod input and I don't know how to create it. could you please advise.
Also what is needed in the metadata file?

thank you

**Comment by liampshaw** [comment]
Noted. This will require some reactivation of my memory on this - expect an
answer by end of the week!

**Comment by antoine4ucsd** [comment]
thank you!

**Comment by liampshaw** [comment]
`alt_alleles_at_site_mod`: the counts of each base code (including ambiguity codes) at every position in the SARS-CoV-2 genome, in the following format (first 150 bp here as [example_data.csv](https://github.com/liampshaw/CoV-homoplasy-filtering/files/9207297/example_data.csv)). Apologies for not providing it / making that clear in the documentation. That was generated by a colleague but I hope it's clear how one might do so from that example.

Metadata: this is metadata as downloaded from GISAID with (at the time we did this analysis) the following column names: `strain	virus	gisaid_epi_isl	genbank_accession	date	region	countrydivision	location	region_exposure	country_exposure	division_exposure	segment	length	host	age	sex	originating_lab	submitting_lab	authors	url	title	date_submitted`. Unfortunately we couldn't provide this due to GISAID rules. I don't remember if all fields are used in the analysis - almost certainly not, so not all are needed. 

I should say that I would recommend against using this code! It's 100% not maintained (I haven't looked at it for 2 years) and you are the first person to raise an issue - which suggests that there may well be other unidentified problems with it in its current state. I'm going to be unlikely to be able to address any other substantive questions you have due to that time gap and not working on this area any more.

**Comment by antoine4ucsd** [comment]
I really appreciate. thank you
